import { IApiResponse, IPaginate } from '@/shared/types/common.types';

export interface ExportReceipt {
    id: string;
    receiptCode?: string;
    warehouseId?: string;
    warehouseName?: string;
    pondId?: string;
    pondName?: string;
    receiverName?: string; // Tên người nhận (nếu có)
    farm?: string; // Alias cho pondName/warehouseName trong UI
    status?: string;
    totalItems?: number;
    totalAmount?: number;
    notes?: string; // Standardized to match ImportReceipt
    approverId?: string | null;
    approvedAt?: string | null;
    isRejected?: boolean;
    autoGenerated?: boolean;
    no?: number;
    createdAt?: string;
    editedAt?: string;
    creator?: any;
    editor?: any;
    materials?: any[]; // To support UI compatibility (even if empty from List API)
}

export interface ExportReceiptItemRequest {
    materialId: string;
    quantity: number;
}

export interface CreateExportReceiptRequest {
    warehouseId: string;
    pondId?: string;
    note?: string;
    documentIds?: string[];
    items: ExportReceiptItemRequest[];
    autoSubmit?: boolean;
}

export interface GetExportReceiptsParams {
    ReceiptCode?: string;
    Status?: string;
    WarehouseId?: string;
    PondId?: string;
    Id?: string;
    CreatedAt?: string;
    CreateAtFrom?: string;
    CreateAtTo?: string;
    Page?: number;
    PageSize?: number;
    OrderBy?: string;
    Search?: string; // Support universal search
}

export type GetExportReceiptsResponse = IApiResponse<IPaginate<ExportReceipt>>;
export type GetExportReceiptByIdResponse = IApiResponse<ExportReceipt>;

export type { GetExportReceiptsParams as GetExportWarehouseParams }; // Alias for backward compatibility if needed
