import { IApiResponse, IPaginate } from '@/shared/types/common.types';

export interface ExportReceiptItem {
    exportReceiptItemId: string;
    materialId: string;
    materialName?: string;
    materialCode?: string;
    unitId?: string;
    unitName?: string;
    quantity: number;
    costPrice: number;
    totalAmount?: number;
}

export interface ExportReceipt {
    id: string;
    receiptCode?: string;
    warehouseId?: string;
    warehouseName?: string;
    pondId?: string;
    pondName?: string;
    zoneId?: string;
    zoneName?: string;
    status?: string;
    totalItems?: number;
    totalAmount?: number;
    note?: string;
    approverId?: string | null;
    approvedAt?: string | null;
    isRejected?: boolean;
    autoGenerated?: boolean;
    recordId?: string;
    relatedInventoryCheckId?: string;
    documentIds?: string[];
    no?: number;
    createdAt?: string;
    editedAt?: string;
    creator?: any;
    editor?: any;
    materials?: ExportReceiptItem[];
    // Deprecated fields kept just in case but should be removed if confirmed unused
    // receiverName?: string;
    // farm?: string;
}

export interface ExportReceiptItemRequest {
    materialId: string;
    quantity: number;
}

export interface CreateExportReceiptRequest {
    warehouseId: string;
    pondId?: string;
    date?: string;
    note?: string;
    documentIds?: string[];
    items: ExportReceiptItemRequest[];
    autoSubmit?: boolean;
}

export interface UpdateExportReceiptRequest {
    receiptId: string;
    warehouseId?: string;
    pondId?: string;
    date?: string;
    note?: string;
    items?: ExportReceiptItemRequest[];
    documentIds?: string[];
}

export interface GetExportReceiptsParams {
    ReceiptCode?: string;
    Status?: string;
    WarehouseId?: string;
    PondId?: string;
    Id?: string;
    CreatedAt?: string;
    CreateAtFrom?: string;
    CreateAtTo?: string;
    Page?: number;
    PageSize?: number;
    OrderBy?: string;
    Search?: string;
}

export type GetExportReceiptsResponse = IApiResponse<IPaginate<ExportReceipt>>;
export type GetExportReceiptByIdResponse = IApiResponse<ExportReceipt>;

export type GetExportReceiptItemsResponse = IApiResponse<ExportReceiptItem[]>;

export type { GetExportReceiptsParams as GetExportWarehouseParams };

// Interface for material option in dropdown
export interface MaterialOption {
    label: string;
    value: string;
    unit: string;
    quantity: number;
    disabled?: boolean;
}

// Interface for warehouse item from API
export interface WarehouseItem {
    materialName?: string;
    materialId?: string;
    unitName?: string;
    quantity?: number;
}

// Interface for useExportMaterials hook params
export interface UseExportMaterialsParams {
    selectedZone: string;
    isEditMode: boolean;
    exportReceiptItems?: ExportReceiptItem[];
}
