import { IApiResponse, IPaginate, ICreatorEditor } from '@/shared/types/common.types';

export enum ExportReceiptStatus {
    Pending = 'Pending',
    Draft = 'Draft',
    Approved = 'Approved',
    Rejected = 'Rejected',
}

export interface ExportReceiptItem {
    exportReceiptItemId: string;
    materialId: string;
    materialName?: string;
    materialCode?: string;
    unitId?: string;
    unitName?: string;
    quantity: number;
    costPrice: number;
    totalAmount?: number;
}

export interface ExportReceipt {
    id: string;
    receiptCode?: string;
    warehouseId?: string;
    warehouseName?: string;
    pondId?: string;
    pondName?: string;
    zoneId?: string;
    zoneName?: string;
    status?: ExportReceiptStatus;
    totalItems?: number;
    totalAmount?: number;
    note?: string;
    approverId?: string | null;
    approvedAt?: string | null;
    isRejected?: boolean;
    autoGenerated?: boolean;
    recordId?: string;
    relatedInventoryCheckId?: string;
    documentIds?: string[];
    no?: number;
    createdAt?: string;
    editedAt?: string;
    creator?: ICreatorEditor | null;
    editor?: ICreatorEditor | null;
    materials?: ExportReceiptItem[];
}

export interface ExportReceiptItemRequest {
    materialId: string;
    quantity: number;
}

export interface CreateExportReceiptRequest {
    warehouseId: string;
    pondId?: string;
    date?: string;
    note?: string;
    documentIds?: string[];
    items: ExportReceiptItemRequest[];
    autoSubmit?: boolean;
}

export interface UpdateExportReceiptRequest {
    receiptId: string;
    warehouseId?: string;
    pondId?: string;
    date?: string;
    note?: string;
    items?: ExportReceiptItemRequest[];
    documentIds?: string[];
}

// Action Types
export interface UpdateExportReceiptItemCommand {
    items: ExportReceiptItemRequest[];
}
export type UpdateExportReceiptItemResponse = IApiResponse<boolean>;

export type DeleteExportReceiptResponse = IApiResponse<boolean>;
export type DeleteExportReceiptItemResponse = IApiResponse<boolean>;

export type SubmitExportReceiptResponse = IApiResponse<boolean>;
export type ApproveExportReceiptResponse = IApiResponse<boolean>;

export interface RejectExportReceiptCommand {
    reason: string;
}
export type RejectExportReceiptResponse = IApiResponse<boolean>;

export interface GetExportReceiptsParams {
    ReceiptCode?: string;
    Status?: string;
    WarehouseId?: string;
    PondId?: string;
    Id?: string;
    CreatedAt?: string;
    CreateAtFrom?: string;
    CreateAtTo?: string;
    Page?: number;
    PageSize?: number;
    OrderBy?: string;
    Search?: string;
}

export type GetExportReceiptsResponse = IApiResponse<IPaginate<ExportReceipt>>;
export type GetExportReceiptByIdResponse = IApiResponse<ExportReceipt>;

// Helper type for flexible response (array or object wrapper)
export type GetExportReceiptItemsResponseData =
    | ExportReceiptItem[]
    | { items: ExportReceiptItem[] };
export type GetExportReceiptItemsResponse = IApiResponse<GetExportReceiptItemsResponseData>;

export type { GetExportReceiptsParams as GetExportWarehouseParams };

// Interface for material option in dropdown
export interface MaterialOption {
    label: string;
    value: string;
    unit: string;
    quantity: number;
    disabled?: boolean;
}

// Interface for warehouse item from API
export interface WarehouseItem {
    materialName?: string;
    materialId?: string;
    unitName?: string;
    quantity?: number;
}

// Interface for useExportMaterials hook params
export interface UseExportMaterialsParams {
    selectedZone: string;
    isEditMode: boolean;
    exportReceiptItems?: ExportReceiptItem[];
}
