import { IApiResponse, IPaginate } from '@/shared/types/common.types';

export enum ImportReceiptStatus {
    Pending = 'Pending',
    Draft = 'Draft',
    Approved = 'Approved',
    Rejected = 'Rejected',
}

export interface ImportReceipt {
    id: string;
    receiptCode?: string;
    status?: ImportReceiptStatus;
    supplierId?: string;
    supplierName?: string;
    warehouseId?: string;
    warehouseName?: string;
    totalItems?: number;
    totalAmount?: number;
    notes?: string;
    approverId?: string | null;
    approvedAt?: string | null;
    isRejected?: boolean;
    autoGenerated?: boolean;
    no?: number;
    createdAt?: string;
    editedAt?: string;
    creator?: any;
    editor?: any;
}

export interface GetImportReceiptsParams {
    ReceiptCode?: string;
    Status?: string;
    SupplierId?: string;
    WarehouseId?: string;
    ApproverId?: string;
    Id?: string;
    CreatedAt?: string;
    CreateAtFrom?: string;
    CreateAtTo?: string;
    Page?: number;
    PageSize?: number;
    OrderBy?: string;
}

export type GetImportReceiptsResponse = IApiResponse<IPaginate<ImportReceipt>>;

export interface ImportReceiptItem {
    materialId: string;
    quantity: number;
    unitPrice: number;
}

export enum ImportSourceEnum {
    Supplier = 'Supplier',
    InternalOperation = 'InternalOperation',
}

export interface CreateImportReceiptRequest {
    supplierId: string;
    warehouseId: string;
    notes?: string;
    autoSubmit: boolean;
    items: ImportReceiptItem[];
    importSourceEnum: ImportSourceEnum;
    documentIds: string[];
    status?: ImportReceiptStatus;
}

export interface IImportMaterialItem {
    id: string;
    materialName: string;
    quantity: string;
    price: string;
    unit?: string;
    // Helper for total calculation
    total?: number;
}

export interface IImportReceipt {
    id: string;
    date: Date | string;
    supplier?: string;
    materials: IImportMaterialItem[];
    totalAmount: number;
    documentIds?: string[];
}

export type CreateImportReceiptResponse = IApiResponse<string>;
