import { IApiResponse, IPaginate, ICreatorEditor } from '@/shared/types/common.types';

export enum ImportReceiptStatus {
    Pending = 'Pending',
    Draft = 'Draft',
    Approved = 'Approved',
    Rejected = 'Rejected',
}

export interface ImportReceipt {
    id: string;
    receiptCode?: string;
    status?: ImportReceiptStatus;
    supplierId?: string;
    supplierName?: string;
    warehouseId?: string;
    warehouseName?: string;
    totalItems?: number;
    totalAmount?: number;
    notes?: string;
    approverId?: string | null;
    approvedAt?: string | null;
    isRejected?: boolean;
    autoGenerated?: boolean;
    no?: number;
    createdAt?: string;
    editedAt?: string;
    creator?: ICreatorEditor | null;
    editor?: ICreatorEditor | null;
}

export interface GetImportReceiptsParams {
    ReceiptCode?: string;
    Status?: string;
    SupplierId?: string;
    WarehouseId?: string;
    ApproverId?: string;
    Id?: string;
    CreatedAt?: string;
    CreateAtFrom?: string;
    CreateAtTo?: string;
    Page?: number;
    PageSize?: number;
    OrderBy?: string;
}

export type GetImportReceiptsResponse = IApiResponse<IPaginate<ImportReceipt>>;

export interface ImportReceiptItem {
    materialId: string;
    quantity: number;
    unitPrice: number;
}

export enum ImportSourceEnum {
    Supplier = 'Supplier',
    InternalOperation = 'InternalOperation',
}

export interface CreateImportReceiptRequest {
    supplierId: string;
    warehouseId: string;
    notes?: string;
    autoSubmit: boolean;
    items: ImportReceiptItem[];
    importSourceEnum: ImportSourceEnum;
    documentIds: string[];
    status?: ImportReceiptStatus;
}

export type CreateImportReceiptResponse = IApiResponse<string>;

export interface ImportReceiptDetailItem {
    id: string;
    importReceiptId: string;
    materialId: string;
    materialName: string;
    materialCode: string;
    quantity: number;
    unitName?: string; // Optional - not always returned by API
    unitPrice: number;
    totalPrice: number;
    no: number;
    creatorId: string | null;
    userCreatorId: string | null;
    editorId: string | null;
    userEditorId: string | null;
    createdAt: string;
    editedAt: string;
    creator: ICreatorEditor | null;
    editor: ICreatorEditor | null;
}

export interface GetImportReceiptItemsParams {
    MaterialName?: string;
    MaterialCode?: string;
    MinQuantity?: number;
    MaxQuantity?: number;
    Id?: string;
    CreatedAt?: string;
    CreateAtFrom?: string;
    CreateAtTo?: string;
    Page?: number;
    PageSize?: number;
    OrderBy?: string;
}

export type GetImportReceiptItemsResponse = IApiResponse<IPaginate<ImportReceiptDetailItem>>;

// ============ Add/Update Item Types ============
export interface CreateImportReceiptItemDto {
    materialId: string;
    quantity: number;
    unitPrice: number;
}

export interface CreateImportReceiptItemCommand {
    items: CreateImportReceiptItemDto[];
}

export interface AddImportReceiptItemResponseDto {
    importReceiptItemId: string;
    materialId: string;
    materialName: string;
    materialCode: string;
    quantity: number;
    unitPrice: number;
    totalPrice: number;
}

export interface AddImportReceiptItemResult {
    id: string;
    no: number;
    creatorId: string | null;
    userCreatorId: string | null;
    editorId: string | null;
    userEditorId: string | null;
    createdAt: string;
    editedAt: string;
    creator: ICreatorEditor | null;
    editor: ICreatorEditor | null;
    items: AddImportReceiptItemResponseDto[];
}

export type AddImportReceiptItemResponse = IApiResponse<AddImportReceiptItemResult>;

export interface UpdateImportReceiptItemDto {
    id?: string; // Optional for new items
    materialId: string;
    quantity: number;
    unitPrice: number;
}

export interface UpdateImportReceiptItemCommand {
    items: UpdateImportReceiptItemDto[];
}

export type UpdateImportReceiptItemResponse = IApiResponse<AddImportReceiptItemResult>;

// ============ Submit/Approve/Reject Types ============
export interface SubmitImportReceiptResult {
    id: string;
    no: number;
    creatorId: string | null;
    userCreatorId: string | null;
    editorId: string | null;
    userEditorId: string | null;
    createdAt: string;
    editedAt: string;
    creator: ICreatorEditor | null;
    editor: ICreatorEditor | null;
}

export type SubmitImportReceiptResponse = IApiResponse<SubmitImportReceiptResult>;
export type ApproveImportReceiptResponse = IApiResponse<SubmitImportReceiptResult>;

export interface RejectImportReceiptCommand {
    reason?: string;
}

export type RejectImportReceiptResponse = IApiResponse<object>;

// ============ Delete Types ============
export type DeleteImportReceiptResponse = IApiResponse<object>;
export type DeleteImportReceiptItemResponse = IApiResponse<object>;
