import { IApiResponse, IPaginate } from '@/shared/types/common.types';

export interface ImportReceipt {
    id: string;
    receiptCode?: string;
    status?: string;
    supplierId?: string;
    supplierName?: string;
    warehouseId?: string;
    warehouseName?: string;
    totalItems?: number;
    totalAmount?: number;
    notes?: string;
    approverId?: string | null;
    approvedAt?: string | null;
    isRejected?: boolean;
    autoGenerated?: boolean;
    no?: number;
    createdAt?: string;
    editedAt?: string;
    creator?: any;
    editor?: any;
}

export interface GetImportReceiptsParams {
    ReceiptCode?: string;
    Status?: string;
    SupplierId?: string;
    WarehouseId?: string;
    Id?: string;
    CreatedAt?: string;
    CreateAtFrom?: string;
    CreateAtTo?: string;
    Page?: number;
    PageSize?: number;
    OrderBy?: string;
}

export type GetImportReceiptsResponse = IApiResponse<IPaginate<ImportReceipt>>;
