# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  # App-Specific Password for App Store Connect
  ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"] = "ekfb-xshp-evsc-zxic"

  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "MebiOne.xcodeproj")
    build_app(workspace: "MebiOne.xcworkspace", scheme: "MebiOne")
    upload_to_testflight(
        apple_id: "6757392489",
        skip_waiting_for_build_processing: true
    )
  end
end
