import { IMaterial } from '../types/material.types';

export const mockMaterialList: IMaterial[] = [
    {
        id: "TV-20251201-01_VT-CP09",
        name: "CP09 – Thức ăn giai đoạn 2",
        group: "Nuôi",
        type: "Thức ăn sống",
        unit: "kg",
        remaining: 482,
        quantity: 1.0,
        unitOfUse: "kg",
        manufacturer: "C.P. Việt Nam",
        usage: "Nuôi tôm GĐ2",
        dosage: "Theo HDSD",
    },
    {
        id: "TV-20251201-02_VT-CP10",
        name: "CP10 – Thức ăn giai đoạn 3",
        group: "Nuôi",
        type: "Thức ăn sống",
        unit: "kg",
        remaining: 398,
        quantity: 1.0,
        unitOfUse: "kg",
        manufacturer: "C.P. Việt Nam",
        usage: "Nuôi tôm GĐ3",
        dosage: "Theo HDSD",
    },
    {
        id: "TV-20251201-03_VT-CP10",
        name: "CP10 – Thức ăn giai đoạn 3",
        group: "Nuôi",
        type: "Thức ăn sống",
        unit: "kg",
        remaining: 398,
        quantity: 0.5,
        unitOfUse: "kg",
        manufacturer: "C.P. Việt Nam",
        usage: "Nuôi tôm GĐ3",
        dosage: "Theo HDSD",
    },
    {
        id: "TV-20251203-02_VT-ZEO",
        name: "Zeolite",
        group: "Vật tư nội bộ",
        type: "Khoáng chất",
        unit: "kg",
        remaining: 198,
        quantity: 10.0,
        unitOfUse: "kg",
        manufacturer: "Hóa Chất Miền Nam",
        usage: "Hấp thụ khí độc, ổn định pH",
        dosage: "20kg/1000m3, 7-10 ngày/lần",
    },
    {
        id: "TV-20251203-02_VT-ZEO2",
        name: "Zeolite Plus",
        group: "Vật tư nội bộ",
        type: "Khoáng chất",
        unit: "kg",
        remaining: 150,
        quantity: 5.0,
        unitOfUse: "kg",
        manufacturer: "Hóa Chất Miền Nam",
        usage: "Giảm khí độc cấp tính",
        dosage: "10-15kg/1000m3 khi cần",
    },
    {
        id: "TV-20251203-02_VT-PROBIO",
        name: "Bioeus Probiotics",
        group: "Vật tư nội bộ",
        type: "Chế phẩm sinh học",
        unit: "lít",
        remaining: 50,
        quantity: 2.0,
        unitOfUse: "lít",
        manufacturer: "Bayer",
        usage: "Gây màu nước, phân hủy mùn",
        dosage: "1 lít/2000m3, 5 ngày/lần",
    },
    {
        id: "XL-9281-AK_VT-NU-13",
        name: "Chlorine 70%",
        group: "Vật tư nội bộ",
        type: "Hoá chất",
        unit: "kg",
        remaining: 100,
        quantity: 50,
        unitOfUse: "kg",
        manufacturer: "NCC Khác",
        usage: "Khử trùng nước cấp đầu vụ",
        dosage: "Theo HDSD",
    },
    {
        id: "XL-3340-PQ_VT-NU-14",
        name: "Iodine 9000",
        group: "Vật tư nội bộ",
        type: "Hoá chất",
        unit: "lít",
        remaining: 20,
        quantity: 2,
        unitOfUse: "lít",
        manufacturer: "NCC Khác",
        usage: "Diệt khuẩn định kỳ",
        dosage: "Theo HDSD",
    },
    {
        id: "XL-1192-XS_VT-NU-15",
        name: "BKC 80%",
        group: "Vật tư nội bộ",
        type: "Hoá chất",
        unit: "lít",
        remaining: 20,
        quantity: 5,
        unitOfUse: "lít",
        manufacturer: "NCC Khác",
        usage: "Diệt tảo độc và sát trùng",
        dosage: "Theo HDSD",
    },
    {
        id: "XL-8873-MZ_VT-NU-16",
        name: "TCCA viên",
        group: "Vật tư nội bộ",
        type: "Hoá chất",
        unit: "kg",
        remaining: 50,
        quantity: 10,
        unitOfUse: "kg",
        manufacturer: "NCC Khác",
        usage: "Xử lý đáy ao lắng",
        dosage: "Theo HDSD",
    },
    {
        id: "XL-3021-LP_VT-NU-19",
        name: "Zeolite hạt",
        group: "Vật tư nội bộ",
        type: "Khoáng chất",
        unit: "kg",
        remaining: 300,
        quantity: 100,
        unitOfUse: "kg",
        manufacturer: "NCC Khác",
        usage: "Hấp thụ khí độc NH3 đáy ao",
        dosage: "Theo HDSD",
    },
    {
        id: "XL-7712-WE_VT-NU-20",
        name: "Saponin",
        group: "Vật tư nội bộ",
        type: "Chất xử lý nước",
        unit: "kg",
        remaining: 100,
        quantity: 20,
        unitOfUse: "kg",
        manufacturer: "NCC Khác",
        usage: "Diệt cá tạp trước khi thả giống",
        dosage: "Theo HDSD",
    },
    {
        id: "XL-5590-RT_VT-NU-21",
        name: "Yucca nước",
        group: "Vật tư nội bộ",
        type: "Chất xử lý nước",
        unit: "lít",
        remaining: 10,
        quantity: 1,
        unitOfUse: "lít",
        manufacturer: "NCC Khác",
        usage: "Cấp cứu tôm nổi đầu buổi đêm",
        dosage: "Theo HDSD",
    },
    {
        id: "XL-2109-BV_VT-NU-22",
        name: "Khoáng tạt tổng hợp",
        group: "Vật tư nội bộ",
        type: "Khoáng chất",
        unit: "kg",
        remaining: 50,
        quantity: 10,
        unitOfUse: "kg",
        manufacturer: "NCC Khác",
        usage: "Bổ sung khoáng giúp lột xác",
        dosage: "Theo HDSD",
    },
    {
        id: "XL-9932-NJ_VT-NU-23",
        name: "Vôi Canxi (CaO)",
        group: "Vật tư nội bộ",
        type: "Khoáng chất",
        unit: "kg",
        remaining: 500,
        quantity: 200,
        unitOfUse: "kg",
        manufacturer: "NCC Khác",
        usage: "Nâng độ Kiềm và ổn định pH",
        dosage: "Theo HDSD",
    },
    {
        id: "XL-4410-XC_VT-NU-24",
        name: "Dolomite",
        group: "Vật tư nội bộ",
        type: "Khoáng chất",
        unit: "kg",
        remaining: 400,
        quantity: 150,
        unitOfUse: "kg",
        manufacturer: "NCC Khác",
        usage: "Ổn định màu nước và hệ đệm",
        dosage: "Theo HDSD",
    },
    {
        id: "XL-20251215-001_VT-ZEO",
        name: "Zeolite",
        group: "Vật tư nội bộ",
        type: "Khoáng chất",
        unit: "kg",
        remaining: 200,
        quantity: 50,
        unitOfUse: "kg",
        manufacturer: "NCC Khác",
        usage: "Hấp thụ khí độc",
        dosage: "Theo HDSD",
    },
    {
        id: "XL-20251215-001_VT-PROBIO",
        name: "Probiotics",
        group: "Vật tư nội bộ",
        type: "Chế phẩm sinh học",
        unit: "lít",
        remaining: 20,
        quantity: 5,
        unitOfUse: "lít",
        manufacturer: "NCC Khác",
        usage: "Cải thiện vi sinh",
        dosage: "Theo HDSD",
    },
    {
        id: "XL-20251216-002_VT-HC01",
        name: "HC01",
        group: "Vật tư nội bộ",
        type: "Hoá chất",
        unit: "lít",
        remaining: 50,
        quantity: 10,
        unitOfUse: "lít",
        manufacturer: "NCC Khác",
        usage: "Khử trùng nước",
        dosage: "Theo HDSD",
    },
    {
        id: "WC-20250112-001_VT-NB-25",
        name: "Dầu Diesel DO",
        group: "CCDC",
        type: "Nhiên liệu",
        unit: "lít",
        remaining: 500,
        quantity: 50,
        unitOfUse: "lít",
        manufacturer: "Petrolimex",
        usage: "N01 - Nhiên liệu chạy máy bơm cấp nước",
        dosage: "Theo định mức máy",
    },
    {
        id: "WC-20250112-002_VT-NB-26",
        name: "Nhớt máy 40",
        group: "CCDC",
        type: "Nhiên liệu",
        unit: "lít",
        remaining: 50,
        quantity: 2,
        unitOfUse: "lít",
        manufacturer: "Castrol",
        usage: "N01 - Thay nhớt định kỳ cho máy nổ",
        dosage: "Theo định mức máy",
    },
    {
        id: "WC-20250115-003_VT-CD-31",
        name: "Motor 2HP",
        group: "Thiết bị điện",
        type: "Thiết bị điện",
        unit: "Cái",
        remaining: 5,
        quantity: 1,
        unitOfUse: "Cái",
        manufacturer: "Toàn Phát",
        usage: "N01 - Lắp mới motor bơm nước cấp",
        dosage: "---",
    },
    {
        id: "WC-20250115-004_VT-CD-32",
        name: "Tủ điện điều khiển",
        group: "Thiết bị điện",
        type: "Thiết bị điện",
        unit: "kg",
        remaining: 2,
        quantity: 1,
        unitOfUse: "kg",
        manufacturer: "NCC Tủ Điện",
        usage: "N02 - Đấu nối hệ thống bơm trung tâm",
        dosage: "---",
    },
    {
        id: "WC-20250115-005_VT-CD-33",
        name: "Dây cáp điện",
        group: "Thiết bị điện",
        type: "Thiết bị điện",
        unit: "Mét",
        remaining: 200,
        quantity: 50,
        unitOfUse: "Mét",
        manufacturer: "Cadivi",
        usage: "N02 - Kéo dây nguồn cho máy bơm đẩy",
        dosage: "---",
    },
    {
        id: "WC-20250115-006_VT-CD-35",
        name: "Máy đo pH cầm tay",
        group: "CCDC",
        type: "Công cụ dụng cụ",
        unit: "kg",
        remaining: 3,
        quantity: 1,
        unitOfUse: "kg",
        manufacturer: "Hanna",
        usage: "N02 - Kiểm tra nước đầu vào trước khi lấy",
        dosage: "---",
    },
    {
        id: "WC-20250115-007_VT-CD-34",
        name: "Bộ Kit test NH3/NO2",
        group: "CCDC",
        type: "Kit kiểm tra chất lượng nước",
        unit: "kg",
        remaining: 10,
        quantity: 2,
        unitOfUse: "kg",
        manufacturer: "Sera",
        usage: "N03 - Kiểm tra khí độc nguồn nước cấp",
        dosage: "---",
    },
    {
        id: "WC-20250115-008_VT-NB-30",
        name: "Dung dịch NV01",
        group: "Vật tư nội bộ",
        type: "Hoá chất",
        unit: "ml",
        remaining: 2000,
        quantity: 500,
        unitOfUse: "ml",
        manufacturer: "NCC Khác",
        usage: "N03 - Vệ sinh đường ống dẫn nước trung tâm",
        dosage: "Theo HDSD",
    },
    {
        id: "WC-20250112-001_VT-HC01",
        name: "HC01",
        group: "Vật tư nội bộ",
        type: "Hoá chất",
        unit: "lít",
        remaining: 50,
        quantity: 2,
        unitOfUse: "lít",
        manufacturer: "NCC Khác",
        usage: "N01 - Bổ sung hóa chất khi cấp nước",
        dosage: "Theo HDSD",
    },
    {
        id: "WC-20250112-002_VT-ZEO",
        name: "Zeolite",
        group: "Vật tư nội bộ",
        type: "Khoáng chất",
        unit: "kg",
        remaining: 198,
        quantity: 5,
        unitOfUse: "kg",
        manufacturer: "Hóa Chất Miền Nam",
        usage: "N02 - Rút bùn, xử lý đáy ao",
        dosage: "20kg/1000m3",
    },
    {
        id: "WC-20250115-003_VT-PROBIO",
        name: "Probiotics",
        group: "Vật tư nội bộ",
        type: "Chế phẩm sinh học",
        unit: "lít",
        remaining: 50,
        quantity: 3,
        unitOfUse: "lít",
        manufacturer: "Bayer",
        usage: "N03 - Thay nước định kỳ, cải thiện vi sinh",
        dosage: "1 lít/2000m3",
    },
];
