import { IMaterial } from '../types/material.types';

export const mockMaterialList: IMaterial[] = [
    {
        id: "TV-20251201-01_VT-CP09",
        name: "CP09 – Thức ăn giai đoạn 2",
        group: "Nuôi",
        type: "Thức ăn sống",
        unit: "kg",
        remaining: 482,
        quantity: 1.0,
        unitOfUse: "kg",
        manufacturer: "C.P. Việt Nam",
        usage: "Nuôi tôm GĐ2",
        dosage: "Theo HDSD",
    },
    {
        id: "TV-20251201-02_VT-CP10",
        name: "CP10 – Thức ăn giai đoạn 3",
        group: "Nuôi",
        type: "Thức ăn sống",
        unit: "kg",
        remaining: 398,
        quantity: 1.0,
        unitOfUse: "kg",
        manufacturer: "C.P. Việt Nam",
        usage: "Nuôi tôm GĐ3",
        dosage: "Theo HDSD",
    },
    {
        id: "TV-20251201-03_VT-CP10",
        name: "CP10 – Thức ăn giai đoạn 3",
        group: "Nuôi",
        type: "Thức ăn sống",
        unit: "kg",
        remaining: 398,
        quantity: 0.5,
        unitOfUse: "kg",
        manufacturer: "C.P. Việt Nam",
        usage: "Nuôi tôm GĐ3",
        dosage: "Theo HDSD",
    },
    {
        id: "TV-20251203-02_VT-ZEO",
        name: "Zeolite",
        group: "Vật tư nội bộ",
        type: "Khoáng chất",
        unit: "kg",
        remaining: 198,
        quantity: 10.0,
        unitOfUse: "kg",
        manufacturer: "Hóa Chất Miền Nam",
        usage: "Hấp thụ khí độc, ổn định pH",
        dosage: "20kg/1000m3, 7-10 ngày/lần",
    },
    {
        id: "TV-20251203-02_VT-ZEO2",
        name: "Zeolite Plus",
        group: "Vật tư nội bộ",
        type: "Khoáng chất",
        unit: "kg",
        remaining: 150,
        quantity: 5.0,
        unitOfUse: "kg",
        manufacturer: "Hóa Chất Miền Nam",
        usage: "Giảm khí độc cấp tính",
        dosage: "10-15kg/1000m3 khi cần",
    },
    {
        id: "TV-20251203-02_VT-PROBIO",
        name: "Bioeus Probiotics",
        group: "Vật tư nội bộ",
        type: "Chế phẩm sinh học",
        unit: "lít",
        remaining: 50,
        quantity: 2.0,
        unitOfUse: "lít",
        manufacturer: "Bayer",
        usage: "Gây màu nước, phân hủy mùn",
        dosage: "1 lít/2000m3, 5 ngày/lần",
    },
    {
        id: "TV-20251201-06_VT-ZEO",
        name: "Zeolite",
        group: "Vật tư nội bộ",
        type: "Khoáng chất",
        unit: "kg",
        remaining: 198,
        quantity: 5.0,
        unitOfUse: "kg",
        manufacturer: "Hóa Chất Miền Nam",
        usage: "Hấp thụ khí độc đáy ao",
        dosage: "20kg/1000m3, 7-10 ngày/lần",
    },
    {
        id: "TV-20251203-03_VT-ZEO2",
        name: "Zeolite Plus",
        group: "Vật tư nội bộ",
        type: "Khoáng chất",
        unit: "kg",
        remaining: 150,
        quantity: 3.0,
        unitOfUse: "kg",
        manufacturer: "Hóa Chất Miền Nam",
        usage: "Xi-phông đáy ao",
        dosage: "10-15kg/1000m3",
    },
    {
        id: "TV-20251203-03_VT-PROBIO",
        name: "Bioeus Probiotics",
        group: "Vật tư nội bộ",
        type: "Chế phẩm sinh học",
        unit: "lít",
        remaining: 50,
        quantity: 1.0,
        unitOfUse: "lít",
        manufacturer: "Bayer",
        usage: "Cải thiện vi sinh",
        dosage: "1 lít/2000m3",
    },
];
